import os
from shutil import copyfile, move

from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider
HTTP = HTTPRemoteProvider()


configfile: "../config/config.yaml"



localrules: all, report, clean

rule all:
    message: "Run entire analysis and compile report."
    input:
        "../report/report.pdf",

if config.get("retrieve_cost_data", True):

    rule retrieve_cost_data:
        input:
            HTTP.remote(
                f"raw.githubusercontent.com/PyPSA/technology-data/{config['costs']['version']}/outputs/costs_{config['costs']['year']}.csv",
                keep_local=True,
            ),
        output:
            "../resources/costs.csv"
        run:
            move(input[0], output[0])


rule import_network:
    input:
        network="../resources/mar_es_only/elec_s_4_ec_lc1.0_Co2L_144H_2030_0.071_DF.nc",
    output:
        network="../resources/export_only/elec_s_4_ec_lc1.0_Co2L_144H_2030_0.071_DF_cleaned.nc",
    script:
        "scripts/import_network.py"

rule plot_figures:
    input:
        gadm_shapes="../resources/shapes/gadm_shapes.geojson"
    output:
        morocco_em="../results/graphics/morocco_em.pdf",
        land_conflicts="../results/graphics/land_conflicts.pdf",
    script:
        "scripts/plot_figures.py"

rule add_esc:
    input:
        network="../resources/export_only/elec_s_4_ec_lc1.0_Co2L_144H_2030_0.071_DF_cleaned.nc",
        tech_costs="../resources/costs.csv",
        shapes_path="../resources/shapes/gadm_shapes.geojson",
    output:
        network="../resources/export_only/elec_s_4_ec_lc1.0_Co2L_144H_2030_0.071_DF_esc_"+str(config["export"]["export_h2"])+".nc",
    script:
        "scripts/add_esc.py"

rule solve_network:
    input:
        network="../resources/export_only/elec_s_4_ec_lc1.0_Co2L_144H_2030_0.071_DF_esc_"+str(config["export"]["export_h2"])+".nc",
    output:
        network="../resources/export_only/elec_s_4_ec_lc1.0_Co2L_144H_2030_0.071_DF_solved_"+str(config["export"]["export_h2"])+".nc",
    script:
        "scripts/solve_network.py"


rule report:
    message: "Compile report."
    input:
        tex="../report/report.tex",
        bib="../report/references.bib",
        morocco_em="../results/graphics/morocco_em.pdf", # Just a placeholder to trigger workflow
        land_conflicts="../results/graphics/land_conflicts.pdf",
    output: "../report/report.pdf"
    shell:
        """
        cd ../report
        pdflatex report.tex
        bibtex report
        pdflatex report.tex
        pdflatex report.tex
        cd ../workflow
        """


rule dag:
     message: "Plot dependency graph of the workflow."
     output:
         dot="../resources/dag.dot",
         pdf="../resources/dag.pdf"
     shell:
         """
         snakemake --rulegraph > {output.dot}
         dot -Tpdf -o {output.pdf} {output.dot}
         """


rule clean:
    message: "Remove all build results but keep downloaded data."
    run:
         import shutil

         shutil.rmtree("../resources")
         shutil.rmtree("../results")
         print("Data downloaded to data/ has not been cleaned.")

        
rule sync:
    params:
        cluster=config["cluster"],
    shell:
        """
        rsync -uvarh --no-g --exclude-from=.syncignore-send . {params.cluster}
        rsync -uvarh --no-g --exclude-from=.syncignore-receive {params.cluster} .
        """
